### ISSUE TITLE
Replace the simple homepage with some colourful design

### ISSUE THREAD

**Issue by sushrut111** [sushrut111/react-grpc-web#6]
- Follow the readme to set up and run the applicaition.
- Start the react app and take a look at the page that shows up. This is a simple page that shows a input box.
- Enhance this application with some good css framework with better design.

**Comment by DreamsOfImran** [comment]
Hey, can I work on this?

**Comment by sushrut111** [comment]
Sure you can @DreamsOfImran 
Let me know if you need some help

**Comment by DreamsOfImran** [comment]
Can you please assign it to me?

**Comment by sushrut111** [comment]
Done

**Comment by DreamsOfImran** [comment]
Created PR for it. Please review.
#7

**Comment by DreamsOfImran** [comment]
You also need to add hacktoberfest tag on your project topic. Also please follow the below steps after review.
https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by sushrut111** [comment]
Thank you, I have updated the topic
